# Generated by Django 4.2.1 on 2023-05-22 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='group',
        ),
    ]
